[package]
name = "miiobin"
version = "0.1.0"
authors = ["Bogdan Olar"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"
openssl = "^0.10.26"